name: Build and Deploy to Firebase

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install root dependencies
        run: npm ci

      - name: Install workspace dependencies
        run: |
          npm install --workspace=functions
          npm install --workspace=public

      - name: Build functions
        run: npm run --workspace=functions build

      - name: Build public assets (SCSS + HTML)
        run: npm run --workspace=public build

      - name: Deploy to Firebase
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FURKANTUNALI_1043 }}"
          channelId: live
          projectId: furkantunali-1043
